spring.application.name=SampleMCPClient
spring.ai.google.genai.api-key=${SPRING_AI_GOOGLE_GENAI_API_KEY}
server.servlet.context-path=/sample-mcp-client
server.port=5050

# mcp specific configuration
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-config/mcp-servers.json